# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [1]:
import numpy as np
import csv

arr = np.load("npfile.npy")
print(arr)

[[ 1  1  1  1  1]
 [ 0 37 35  7  4]
 [ 0 37 37 10  4]
 [ 0 37 30 78  4]
 [ 0 35 26 42  4]
 [ 0 36 28 14  4]
 [ 0 36 31 36  5]
 [ 0 37 30 50  4]
 [ 0 36 27  6  4]
 [ 0 38 26 11  4]
 [ 0 37 36 10  4]
 [ 0 35 26 28  4]
 [ 0 37 36 15  4]
 [ 0 37 36 10  4]
 [ 0 37 26  4  4]
 [ 0 37 29 17  4]
 [ 0 39 44  7  4]
 [ 0 38 44 10  4]
 [ 0 35 28  6  4]
 [ 0 37 37 10  4]]


2. Display the mean and the standard deviation for each column.

In [2]:
for x in range(arr.shape[0]):
    print("{}. coloumn's mean ------> {:.2}".format(x,np.mean(arr[x])))
    print("{}. coloums's standart deviation --> {:.2f}".format(x,np.std(arr[x])))
    

0. coloumn's mean ------> 1.0
0. coloums's standart deviation --> 0.00
1. coloumn's mean ------> 1.7e+01
1. coloums's standart deviation --> 16.01
2. coloumn's mean ------> 1.8e+01
2. coloums's standart deviation --> 16.16
3. coloumn's mean ------> 3e+01
3. coloums's standart deviation --> 28.03
4. coloumn's mean ------> 2.1e+01
4. coloums's standart deviation --> 16.68
5. coloumn's mean ------> 1.6e+01
5. coloums's standart deviation --> 13.76
6. coloumn's mean ------> 2.2e+01
6. coloums's standart deviation --> 15.78
7. coloumn's mean ------> 2.4e+01
7. coloums's standart deviation --> 19.27
8. coloumn's mean ------> 1.5e+01
8. coloums's standart deviation --> 14.22
9. coloumn's mean ------> 1.6e+01
9. coloums's standart deviation --> 14.20
10. coloumn's mean ------> 1.7e+01
10. coloums's standart deviation --> 15.92
11. coloumn's mean ------> 1.9e+01
11. coloums's standart deviation --> 13.94
12. coloumn's mean ------> 1.8e+01
12. coloums's standart deviation --> 15.58
13. coloumn's

3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [4]:
arr = np.load("npfile.npy")

print(arr[16])
arr = arr -[1,25,25,10,4]
print(arr[16])

[ 0 39 44  7  4]
[-1 14 19 -3  0]


4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [5]:
arr = np.load("npfile.npy")
print(arr[16])
arr = arr*2
print(arr[16])

[ 0 39 44  7  4]
[ 0 78 88 14  8]
