# <font color=blue>Assignments for "Indexing and Slicing of NumPy Arrays"</font>

For the assignment, you are going to use [Earthquakes](https://bootrain-lms-assets.s3.eu-central-1.amazonaws.com/bootrain-lms-static/datasets/Earthquakes.csv) dataset.

1. Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [3]:
import numpy as np
import csv

with open('Earthquakes.csv') as csvfile:
    csv_reader = csv.reader(csvfile, quotechar='"', quoting = csv.QUOTE_MINIMAL)
    line_count = 0
    lst = []
    for row in csv_reader:
        lst.append(list(map(int,map(float,row))))

    arr = np.array(lst) 
    print(arr)
    
    
                  


[[   0    0    0 ...    4    7    0]
 [   1    0    0 ...    4    7    0]
 [   2    0    0 ...    4    7    0]
 ...
 [6571    4    0 ...    4    2    0]
 [6572    3    0 ...    5    2    0]
 [6573    2    0 ...    4    2    0]]


2. Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [4]:
new_array = arr[0:20,(3,5,6,7,12)]
print(new_array)

[[ 0 36 44 16  4]
 [ 0 37 35  7  4]
 [ 0 37 37 10  4]
 [ 0 37 30 78  4]
 [ 0 35 26 42  4]
 [ 0 36 28 14  4]
 [ 0 36 31 36  5]
 [ 0 37 30 50  4]
 [ 0 36 27  6  4]
 [ 0 38 26 11  4]
 [ 0 37 36 10  4]
 [ 0 35 26 28  4]
 [ 0 37 36 15  4]
 [ 0 37 36 10  4]
 [ 0 37 26  4  4]
 [ 0 37 29 17  4]
 [ 0 39 44  7  4]
 [ 0 38 44 10  4]
 [ 0 35 28  6  4]
 [ 0 37 37 10  4]]


3. Display the row numbers where last values are equal to 4.5 or higher.

In [5]:
print(new_array[5:,:])

[[ 0 36 28 14  4]
 [ 0 36 31 36  5]
 [ 0 37 30 50  4]
 [ 0 36 27  6  4]
 [ 0 38 26 11  4]
 [ 0 37 36 10  4]
 [ 0 35 26 28  4]
 [ 0 37 36 15  4]
 [ 0 37 36 10  4]
 [ 0 37 26  4  4]
 [ 0 37 29 17  4]
 [ 0 39 44  7  4]
 [ 0 38 44 10  4]
 [ 0 35 28  6  4]
 [ 0 37 37 10  4]]


4. Assign 1 to first row.

In [6]:
new_array[0,:]=1
print(new_array)
print(new_array.shape)

[[ 1  1  1  1  1]
 [ 0 37 35  7  4]
 [ 0 37 37 10  4]
 [ 0 37 30 78  4]
 [ 0 35 26 42  4]
 [ 0 36 28 14  4]
 [ 0 36 31 36  5]
 [ 0 37 30 50  4]
 [ 0 36 27  6  4]
 [ 0 38 26 11  4]
 [ 0 37 36 10  4]
 [ 0 35 26 28  4]
 [ 0 37 36 15  4]
 [ 0 37 36 10  4]
 [ 0 37 26  4  4]
 [ 0 37 29 17  4]
 [ 0 39 44  7  4]
 [ 0 38 44 10  4]
 [ 0 35 28  6  4]
 [ 0 37 37 10  4]]
(20, 5)


5. Save the final state of the array to disk. You are going to use this in the next assignment.

In [7]:
np.save("npfile",new_array)