# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [66]:
import numpy as np
import csv

arr = np.load("npfile.npy")
print(arr)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  0  0  0  0 37 35  7  0  7  0  0  4  7  0]
 [ 2  0  0  0  0 37 37 10  0  7  0  0  4  7  0]
 [ 3  0  0  0  0 37 30 78  0  7  0  0  4  7  0]
 [ 4  0  0  0  0 35 26 42  0  7  0  0  4  7  0]
 [ 5  0  0  0  0 36 28 14  0  7  0  0  4  7  0]
 [ 6  0  0  0  0 36 31 36  0  7  0  0  5  7  0]
 [ 7  0  0  0  0 37 30 50  0  7  0  0  4  7  0]
 [ 8  0  0  0  0 36 27  6  0  7  0  0  4  7  0]
 [ 9  0  0  0  0 38 26 11  0  7  0  0  4  7  0]
 [10  0  0  0  0 37 36 10  0  7  0  0  4  7  0]
 [11  0  0  0  0 35 26 28  0  7  0  0  4  7  0]
 [12  0  0  0  0 37 36 15  0  7  0  0  4  7  0]
 [13  0  0  0  0 37 36 10  0  7  0  0  4  7  0]
 [14  0  0  0  0 37 26  4  0  7  0  0  4  7  0]
 [15  0  0  0  0 37 29 17  0  7  0  0  4  7  0]
 [16  0  0  0  0 39 44  7  0  7  0  0  4  7  0]
 [17  0  0  0  0 38 44 10  0  7  0  0  4  7  0]
 [18  0  0  0  0 35 28  6  0  7  0  0  4  7  0]
 [19  0  0  0  0 37 37 10  0  7  0  0  4  7  0]
 [ 3  0  0  0  0 37 30 78  0  7  0  0  4

2. Display the mean and the standard deviation for each column.

In [65]:
for x in range(arr.shape[0]):
    print("{}. coloumn's mean ------> {:.2}".format(x,np.mean(arr[x])))
    print("{}. coloums's standart deviation --> {:.2f}".format(x,np.std(arr[x])))
    

0. coloumn's mean ------> -3.8e+01
0. coloums's standart deviation --> 30.65
1. coloumn's mean ------> -3.8e+01
1. coloums's standart deviation --> 30.65
2. coloumn's mean ------> -3.8e+01
2. coloums's standart deviation --> 30.65
3. coloumn's mean ------> -3.9e+01
3. coloums's standart deviation --> 30.89
4. coloumn's mean ------> -2.2e+01
4. coloums's standart deviation --> 34.43
5. coloumn's mean ------> -3.7e+01
5. coloums's standart deviation --> 30.25
6. coloumn's mean ------> -3.9e+01
6. coloums's standart deviation --> 31.13
7. coloumn's mean ------> -2.1e+01
7. coloums's standart deviation --> 33.43
8. coloumn's mean ------> -3.7e+01
8. coloums's standart deviation --> 30.25
9. coloumn's mean ------> -3.8e+01
9. coloums's standart deviation --> 31.37
10. coloumn's mean ------> -8.6
10. coloums's standart deviation --> 27.37
11. coloumn's mean ------> -3.7e+01
11. coloums's standart deviation --> 30.25
12. coloumn's mean ------> -3.8e+01
12. coloums's standart deviation --> 31.

3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [69]:
arr = np.load("npfile.npy")
arr = arr.reshape(75,5)
print(arr[16])
arr = arr -[1,25,25,10,4]
print(arr[16])

[36 28 14  0  7]
[ 35   3 -11 -10   3]


4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [70]:
arr = np.load("npfile.npy")
print(arr[16])
arr = arr*2
print(arr[16])

[16  0  0  0  0 39 44  7  0  7  0  0  4  7  0]
[32  0  0  0  0 78 88 14  0 14  0  0  8 14  0]
