# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [16]:
import numpy as np

house_square = np.array([100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400,420,440,460,480])
rooms = np.array([1,2,4,6,8,10,12,14,16,18,18,18,8,10,10,10,10,10,10,10])
price = np.array([100000,120000,140000,160000,180000,200000,220000,240000,2600000,280000,300000,
                  320000,340000,3600000,3800000,4000000,4200000,4400000,4600000,4800000])

houses = np.array([house_square,rooms,price])
print(houses)

[[    100     120     140     160     180     200     220     240     260
      280     300     320     340     360     380     400     420     440
      460     480]
 [      1       2       4       6       8      10      12      14      16
       18      18      18       8      10      10      10      10      10
       10      10]
 [ 100000  120000  140000  160000  180000  200000  220000  240000 2600000
   280000  300000  320000  340000 3600000 3800000 4000000 4200000 4400000
  4600000 4800000]]


2. Transpose the array you have created, so that every line can represent features of one house.

In [17]:
houses = houses.T
print(houses)

[[    100       1  100000]
 [    120       2  120000]
 [    140       4  140000]
 [    160       6  160000]
 [    180       8  180000]
 [    200      10  200000]
 [    220      12  220000]
 [    240      14  240000]
 [    260      16 2600000]
 [    280      18  280000]
 [    300      18  300000]
 [    320      18  320000]
 [    340       8  340000]
 [    360      10 3600000]
 [    380      10 3800000]
 [    400      10 4000000]
 [    420      10 4200000]
 [    440      10 4400000]
 [    460      10 4600000]
 [    480      10 4800000]]


3. Display the shape of the array and explain what it means.

In [19]:
print(houses.shape)

(20, 3)


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [33]:
arr = np.full((6,5),1)

for i in range(1,arr.shape[0]+1):
    for j in range(1,arr.shape[1]+1):
        if(i%2 == 0 and j%2==0):
            arr[i-1][j-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]]
